config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard", as: :dashboard

  get "up" => "rails/health#show", as: :rails_health_check

  resources :skills, only: [:index, :show, :new, :edit, :update, :create] do
    resources :bookings, only: [:new, :create, :update]
  end

  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end

  resources :skills, only: [:destroy], as: :destroy_skill
  resources :bookings, only: [:destroy]
  resources :reviews, only: [:destroy]

  patch "/booking/:id", to: "booking#status_update", as: :status_update

  resources :chatrooms, only: [:index, :show] do
    member do
      patch :mark_as_read, to: 'chatrooms#mark_as_read'
    end
  end

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :booking
  validates :booking_id, uniqueness: true

  has_many :messages, dependent: :destroy

  def has_unread_messages?
    messages.where(read: false).exists?
  end

  def unread_messages_count_for(user)
    messages.where(read: false).where.not(user: user).count
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
    def index
      @chatrooms = Chatroom.all
    end
  
    def show
      @chatroom = Chatroom.find(params[:id])
      @name = @chatroom.booking.user == current_user ? @chatroom.booking.skill.user.first_name.capitalize : @chatroom.booking.user.first_name.capitalize
      @message = Message.new
      respond_to do |format|
        format.html
        format.json do
          response = {
            html: render_to_string(partial: "shared/chatroom", locals: { chatroom: @chatroom }, formats: :html, layout: false)
          }
          render json: response.to_json
        end
      end
    end
  
    def mark_as_read
      @chatroom = Chatroom.find(params[:id])
      @chatroom.messages.where(read: false).where.not(user: current_user).update_all(read: true)
      head :ok
    end
  end
  

app/views/chatrooms/index.html.erb
<h1>Tous les salons de discussion</h1>
<ul>
  <% @chatrooms.each do |chatroom| %>
    <li><%= link_to chatroom.name, chatroom_path(chatroom) %></li>
  <% end %>
</ul>


app/views/chatrooms/show.html.erb
<div class="chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">
    <h1>Discutez avec <%= @name %> à propos <%= @chatroom.booking.skill.name %></h1>
  
<div class="messages" data-chatroom-subscription-target="messages">
 <% @chatroom.messages.each do |message| %>
  <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
    <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
      <%= render "messages/message", message: message %>
    </div>
  </div>
<% end %>
  </div>
  <%= simple_form_for [@chatroom, @message],
  html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
%>
  <%= f.input :content,
    label: false,
    placeholder: "Message ##{@chatroom.name}",
    wrapper_html: {class: "flex-grow-1"}
  %>
  <%= f.submit "Send", class: "btn btn-primary mb-3" %>
<% end %>
</div>