config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard", as: :dashboard

  get "up" => "rails/health#show", as: :rails_health_check

  resources :skills, only: [:index, :show, :new, :edit, :update, :create] do
    resources :bookings, only: [:new, :create, :update]
  end

  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end

  resources :skills, only: [:destroy], as: :destroy_skill
  resources :bookings, only: [:destroy]
  resources :reviews, only: [:destroy]

  patch "/booking/:id", to: "booking#status_update", as: :status_update

  resources :chatrooms, only: [:index, :show] do
    member do
      patch :mark_as_read, to: 'chatrooms#mark_as_read'
    end
  end

end

app/views/shared/_animation_accept_modal.html.erb
  <div class="modal fade" id="animationAccept" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true", style="--bs-modal-bg: #00000000 !important;">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content border-0">
      <div class="modal-header" hidden="true">
        <!--<h1 class="modal-title fs-5 text-light" id="exampleModalLabel">Vous venez de gagner 1 crédit en acceptant ce cours !</h1>-->
        <!--<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>-->
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-center">
          <div><%= image_tag 'ruby-gif.gif', alt: "Credit turning around" %></div>
        </div>
          <div class="d-flex align-items-center flex-column">
            <h1 class="text-light fs-1">+1</h1>
            <h3 class="text-light fs-5 mt-2">Vous venez de gagner 1 crédit en acceptant ce cours !</h3>
            <button id="close-modal"type="button" class="btn-close mt-2 bg-dark-subtle rounded-circle p-2" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
      </div>
      <div class="modal-footer" hidden="true">
      </div>
    </div>
  </div>
</div>

app/views/shared/_avatar_image.html.erb
<% if current_user && current_user.photo.attached? %>
  <%= cl_image_tag current_user.photo.key %>
<% else %>
  <%= image_tag("https://xsgames.co/randomusers/avatar.php?g=pixel") %>
<% end %>

app/views/shared/_bookings_student.html.erb
<%= render "shared/incoming_student_bookings" %>


<%= render "shared/past_student_bookings" %>

app/views/shared/_card.html.erb
<%= link_to skill_path(user.skills.first), class:"text-decoration-none text-reset", data: { turbo: false } do %>

  <div class="card">
      <div class="top-part" style="background-image: url('<%= user.photo.attached? ? cl_image_path(user.photo.key) : "https://images.unsplash.com/photo-1610429419519-8cdee5a8e615?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fHBpYW5pc3RlfGVufDB8fDB8fHww" %>')">
      </div>

      <div class="card-name">
          <h3><%=user.first_name %> <%=user.last_name %></h3>
      </div>
      <div class="bottom-part">
              <div class="details">
                <% skill = user.skills.first %>
                    <ul class="tags">
                        <% user.skills.each do |skill| %>
                        <li><%= skill&.name.capitalize %></li>
                        <% end %>
                    </ul>
                  <p>💼</i> <%= skill&.experience_year  %> ans d'expérience</p>
                  <p>⭐</i> <%= rand(2..5).to_f %>/5</p>
              </div>
      </div>
  </div>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="notice">
    <span class="me-3"><strong>Bravo ! </strong><%= notice %></span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_home_navbar.html.erb
<div class="home-navbar">
  <%=link_to root_path do%>
    <%= image_tag "logo_passetemps.png", class:"logo"%>
  <% end %>
  <div class="pe-3">
    <%if current_user%>
      <%= link_to "Mon Espace", dashboard_path, class:"text-light px-2 text-decoration-none"%>
    <%else%>
      <%= link_to "Se Connecter", new_user_session_path, class:"text-black px-2 text-decoration-none"%>
      <%= link_to "S'inscrire", new_user_registration_path, class:"text-black px-2 text-decoration-none"%>
    <%end%>
  </div>
</div>

app/views/shared/_inbox.html.erb
<div class="inbox-wrapper" id="inbox-wrapper" data-controller="inbox chat">
  <div class="d-flex flex-column-reverse align-items-end ">
    <i class="fa-solid fa-comments bubble" data-action="click->inbox#toggle" data-inbox-target="inboxLinksClose"></i>
    <div class="wrapper-links inbox-links-close">
      <% unless @chatrooms.nil? %>
        <% @chatrooms.each do |chatroom| %>
          <div data-action="click->chat#reveal" class="inbox-link" data-chat-id="<%= chatroom.id %>">
            <div class="inbox-avatar">
                <%= cl_image_tag chatroom.booking.other_user(current_user).photo.key, class: "avatar-image receiver-avatar" %>
            </div>
            <div class="inbox-user-info">
              <% other_user = chatroom.booking.other_user(current_user) %>
              <p class="inbox-user-name"><%= other_user.first_name.capitalize %></p>
              <p class="inbox-user-skill"><%= chatroom.booking.skill.name.downcase %> - <%= chatroom.booking.start_date.strftime("%d/%m/%Y") %></p>
            </div>
            <% unread_count = chatroom.unread_messages_count_for(current_user) %>
            <% if unread_count > 0 %>
              <div class="unread-indicator">
                <%= unread_count %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="inbox-chat" id="test" data-controller="chat-container" data-close-icon-target="inboxChat">
  </div>
</div>

app/views/shared/_incoming_student_bookings.html.erb
<div class="row align-items-baseline">
  <%= image_tag "calendar-icon-two.png", style:"object-fit:contain;width:60px;", class:"col-6" %>
  <h3 class="mt-5 col-6">Mes prochains cours </h3>
</div>

<% if current_user.bookings.where('start_date >= ?', Date.today).count == 0 %>
  <p>Vous n'avez pas de réservation pour le moment. Trouvez un professeur à réserver !</p>
  <%= link_to "Je trouve mon futur professeur !", skills_path, class:"btn btn-secondary rounded-5" %>
<% else %>

  <table class="table table-hover bg-transparent">
    <thead>
      <tr>
        <th scope="col", class="bg-transparent">#</th>
        <th scope="col", class="bg-transparent">Compétence</th>
        <th scope="col", class="bg-transparent">Nom du professeur</th>
        <th scope="col", class="bg-transparent">Date</th>
        <th scope="col", class="bg-transparent">Horaire de début</th>
        <th scope="col", class="bg-transparent">Statut de la réservation</th>
        <th scope="col", class="bg-transparent"></th>
        <th scope="col", class="bg-transparent"></th>
      </tr>
    </thead>
    <tbody>
  <% current_user.bookings.reverse.each_with_index do |booking, index| %>
    <% if (Date.today <= booking.start_date && booking.status == "confirmed") || (Date.today <= booking.start_date && booking.status == "pending") %>
        <div>
          <tr data-controller="table-links" value="<%= booking_path(booking) %>" data-action="click->table-links#show" data-table-links-target="link">
            <th scope="row", class="bg-transparent"><%= index + 1 %></th>
            <td class="bg-transparent"><%= booking.skill.name.capitalize %></td>
            <td class="bg-transparent"><%= booking.skill.user.first_name %></td>
            <td class="bg-transparent"><%= booking.start_date.strftime("%d/%m/%Y") %></td>
            <td class="bg-transparent"><%= booking.start_date.strftime("%R") %></td>
            <td class="bg-transparent">
              <div class="booking-status rounded-pill px-2 text-light <%= booking.status == 'pending' ? 'orange' : (booking.status == 'confirmed' ? 'green' : 'red') %>"">
                <%= t(booking.status) %>
              </div>
            </td>
            <td class="bg-transparent"><%= link_to "Afficher les détails", booking_path(booking), class:"text-decoration-none" %></td>
            <td class="bg-transparent"><%= link_to "Supprimer", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Êtes vous sûrs?" }, class:"text-decoration-none" %></td>
          </tr>
        </div>
    <% end %>
  <% end %>
    </tbody>
  </table>

<% end %>

app/views/shared/_incoming_teacher_bookings.html.erb
<div class="row align-items-baseline">
  <%= image_tag "calendar-icon-two.png", style:"object-fit:contain;width:60px", class:"col-6" %>
  <h3 class="mt-5 col-6">Mes prochains cours </h3>
</div>

<%# if current_user.bookings_as_teacher.where('start_date > ?', Time.now.to_datetime).count == 0 %>
<!--  <p>You don't have any booked courses with student right now.</p>-->
<%# else %>

  <div data-insert-in-list-target="bookings">
    <table class="table table-hover bg-transparent">
      <thead>
        <tr>
          <th scope="col", class="bg-transparent">#</th>
          <th scope="col", class="bg-transparent">Compétence</th>
          <th scope="col", class="bg-transparent">Nom de l'élève</th>
          <th scope="col", class="bg-transparent">Date</th>
          <th scope="col", class="bg-transparent">Horaire de début</th>
          <th scope="col", class="bg-transparent">Statut de la réservation</th>
          <th scope="col", class="bg-transparent"></th>
          <th scope="col", class="bg-transparent"></th>
        </tr>
      </thead>
      <tbody>
    <% current_user.bookings_as_teacher.reverse.each_with_index do |booking, index| %>
      <% if Date.today <= booking.start_date && booking.status == "confirmed" %>
          <div>
            <tr data-controller="table-links" value="<%= booking_path(booking) %>" data-action="click->table-links#show" data-table-links-target="link">
              <th scope="row", class="bg-transparent"><%= index + 1 %></th>
              <td class="bg-transparent"><%= booking.skill.name.capitalize %></td>
              <td class="bg-transparent"><%= booking.skill.user.first_name %></td>
              <td class="bg-transparent"><%= booking.start_date.strftime("%d/%m/%Y") %></td>
              <td class="bg-transparent"><%= booking.start_date.strftime("%R") %></td>
              <td class="bg-transparent">
                <div class="booking-status rounded-pill px-2 text-light <%= booking.status == 'pending' ? 'orange' : (booking.status == 'confirmed' ? 'green' : 'red') %>"">
                <%= t(booking.status) %>
              </div>
              </td>
              <td class="bg-transparent"><%= link_to "Détails", booking_path(booking), class:"text-decoration-none" %></td>
              <td class="bg-transparent"><%= link_to "Supprimer", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"text-decoration-none" %></td>
            </tr>
          </div>
      <% end %>
    <% end %>
      </tbody>
    </table>


    <div class="row align-items-baseline">
  <%= image_tag "warning-icon.png", style:"object-fit:contain;width:60px", class:"col-6" %>
  <h3 class="mt-5 col-6">Demandes de cours à traiter</h3>
</div>

  <table class="table table-hover bg-transparent">
      <thead>
        <tr>
          <th scope="col", class="bg-transparent">#</th>
          <th scope="col", class="bg-transparent">Compétence</th>
          <th scope="col", class="bg-transparent">Nom de l'élève</th>
          <th scope="col", class="bg-transparent">Date</th>
          <th scope="col", class="bg-transparent">Horaire de début</th>
          <th scope="col", class="bg-transparent">Statut de la réservation</th>
          <th scope="col", class="bg-transparent"></th>
          <th scope="col", class="bg-transparent"></th>
        </tr>
      </thead>
      <tbody>
    <% current_user.bookings_as_teacher.reverse.each_with_index do |booking, index| %>
      <% if booking.status == "pending" %>
          <div>
            <tr data-controller="table-links" value="<%= booking_path(booking) %>" data-action="click->table-links#show" data-table-links-target="link">
              <th scope="row", class="bg-transparent"><%= index + 1 %></th>
              <td class="bg-transparent"><%= booking.skill.name.capitalize %></td>
              <td class="bg-transparent"><%= booking.user.first_name %></td>
              <td class="bg-transparent"><%= booking.start_date.strftime("%d/%m/%Y") %></td>
              <td class="bg-transparent"><%= booking.start_date.strftime("%R") %></td>
              <td class="bg-transparent">
                <div class="booking-status rounded-pill px-2 text-light <%= booking.status == 'pending' ? 'orange' : (booking.status == 'confirmed' ? 'green' : 'red') %>"">
                <%= t(booking.status) %>
              </div>
              </td>
              <td class="bg-transparent"><%= link_to "Détails", booking_path(booking), class:"text-decoration-none" %></td>
              <td class="bg-transparent">

              <%= render "bookings/form_accept", booking: booking %>


              </td>
              <td class="bg-transparent">

              <%= render "bookings/form_refuse", booking: booking %>

              </td>
            </tr>
          </div>
      <% end %>
    <% end %>
      </tbody>
    </table>



  <div class="row align-items-baseline">
  <%= image_tag "historical.png", style:"object-fit:contain;width:60px", class:"col-6" %>
  <h3 class="mt-5 col-6">Mes cours passés </h3>
</div>
  <table class="table table-hover bg-transparent">
      <thead>
        <tr>
          <th scope="col", class="bg-transparent">#</th>
          <th scope="col", class="bg-transparent">Compétence</th>
          <th scope="col", class="bg-transparent">Nom de l'élève</th>
          <th scope="col", class="bg-transparent">Date</th>
          <th scope="col", class="bg-transparent">Horaire de début</th>
          <th scope="col", class="bg-transparent">Statut de la réservation</th>
          <th scope="col", class="bg-transparent"></th>
          <th scope="col", class="bg-transparent"></th>
        </tr>
      </thead>
      <tbody>
    <% current_user.bookings_as_teacher.reverse.each_with_index do |booking, index| %>
      <% if Date.today > booking.start_date && (booking.status == "rejected" || booking.status == "confirmed") %>
          <div>
            <tr data-controller="table-links" value="<%= booking_path(booking) %>" data-action="click->table-links#show" data-table-links-target="link">
              <th scope="row", class="bg-transparent"><%= index + 1 %></th>
              <td class="bg-transparent"><%= booking.skill.name.capitalize %></td>
              <td class="bg-transparent"><%= booking.user.first_name %></td>
              <td class="bg-transparent"><%= booking.start_date.strftime("%d/%m/%Y") %></td>
              <td class="bg-transparent"><%= booking.start_date.strftime("%R") %></td>
              <td class="bg-transparent">
                <div class="booking-status rounded-pill px-2 text-light <%= booking.status == 'pending' ? 'orange' : (booking.status == 'confirmed' ? 'green' : 'red') %>"">
                <%= t(booking.status) %>
              </div>
              </td>
              <td class="bg-transparent"><%= link_to "Détails", booking_path(booking), class:"text-decoration-none" %></td>
              <td class="bg-transparent"><%= link_to "Supprimer", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"text-decoration-none" %></td>
            </tr>
          </div>
      <% end %>
    <% end %>
      </tbody>
    </table>
  </div>

app/views/shared/_marker.html.erb
<%= image_tag "custom_pointer.png", height: 50, width: 50, alt: "Pointer" %>

app/views/shared/_past_student_bookings.html.erb
<% if current_user.bookings.where('start_date < ?', Date.today).count == 0 %>
  <p class="mt-5">Pas d'historique de cours suivis pour le moment</p>
<% else %>

  <div class="row align-items-baseline">
  <%= image_tag "historical.png", style:"object-fit:contain;width:60px", class:"col-6" %>
  <h3 class="mt-5 col-6">Mes cours passés </h3>
</div>

  <table class="table table-hover bg-transparent">
    <thead>
      <tr>
        <th scope="col", class="bg-transparent">#</th>
        <th scope="col", class="bg-transparent">Compétence</th>
        <th scope="col", class="bg-transparent">Nom du professeur</th>
        <th scope="col", class="bg-transparent">Date</th>
        <th scope="col", class="bg-transparent">Horaire de début</th>
        <th scope="col", class="bg-transparent">Statut de la réservation</th>
        <th scope="col", class="bg-transparent"></th>
        <th scope="col", class="bg-transparent"></th>
      </tr>
    </thead>
    <tbody>

  <% current_user.bookings.reverse.each_with_index do |booking, index| %>
    <% if Date.today > booking.start_date %>
        <div>
          <tr data-controller="table-links" value="<%= booking_path(booking) %>" data-action="click->table-links#show" data-table-links-target="link">
            <th scope="row", class="bg-transparent"><%= index + 1 %></th>
            <td class="bg-transparent"><%= booking.skill.name.capitalize %></td>
            <td class="bg-transparent"><%= booking.skill.user.first_name %></td>
            <td class="bg-transparent"><%= booking.start_date.strftime("%d/%m/%Y") %></td>
            <td class="bg-transparent"><%= booking.start_date.strftime("%R") %></td>
            <td class="bg-transparent">
              <div class="booking-status rounded-pill px-2 text-light <%= booking.status == 'pending' ? 'orange' : (booking.status == 'confirmed' ? 'green' : 'red') %>"">
                <%= t(booking.status) %>
              </div>
            </td>
            <td class="bg-transparent"><%= link_to "Afficher les détails", booking_path(booking), class:"text-decoration-none" %></td>
            <td class="bg-transparent"><%= link_to "Supprimer", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Êtes vous sûrs?" }, class:"text-decoration-none" %></td>
          </tr>
        </div>
    <% end %>
  <% end %>
    </tbody>
  </table>

<% end %>

app/views/shared/_search_by_category_carousel.html.erb
<div class="mx-auto search-by-category-container py-3 px-3 mt-5">
  <div class="d-flex search-by-category-list justify-content-center">
    <% @skills.select("distinct category, icon").each do |skill| %>
      <% if skill.icon.present? %>
        <div class="search-by-category-item">
          <%= link_to skills_path(category: skill.category), class: "d-flex flex-column align-items-center p-2 text-decoration-none" do %>
            <!-- <i class="fa-regular fa-heart text-white pb-2"></i> -->
            <%= skill.icon %>
            <div class="category-name">
              <%= skill.category %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_searchbar.html.erb
  <div class="custom-searchbar-display">
    <%= form_with url: skills_path, method: :get, class: "d-flex", data: { turbo: false } do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-input custom-searchbar",
            placeholder: Skill.all.sample.name.capitalize
        %>
      <%= submit_tag "Rechercher", name: "", class: "btn custom-searchbar-button" %>
    <% end %>
  </div>

app/views/shared/_skills.html.erb
<h2>Compétence</h2>
<% if current_user.skills.any? %>
  <% current_user.skills.each do |skill| %>
    <li><%= skill.name.capitalize %> | <%= skill.category %> || <%= link_to "Modifer", edit_skill_path(skill) %> / <%= link_to "Supprimer", destroy_skill_path(skill), data: { turbo_method: :delete, turbo_confirm: "Êtes vous sûrs?" } %></li>
  <% end %>
<% end %>